### ISSUE TITLE
Venn Diagram Doesn't come up

### ISSUE THREAD

**Issue by kailashjoshi018** [gcalvo1/looker-custom-visualizations#1]
Hi,

I imported the js which you provided here to my looker and now I can see the visualization type. But, I am not able to load the visualization. I have created a new data set which has dimension with " & " in it's values and a measure to count these values.

However, the venn diagram doesn't come up. Could you please help me here.

TIA!!

**Comment by kailashjoshi018** [comment]
had to import d3.js module to looker and worked perfectly. Closing this issue.

**Comment by MishraAnmol** [comment]
Hey @kailashjoshi018 can you help with this issue.
What do you mean when you say "imported d3.js module". Where did you find this JS file and where did you place it for importing to happen.
I am also facing the same issue as you, so let me know this, it might help me.
Thanks in Advance.

**Comment by doublec1985** [comment]
Did you ever get an answer here I am trying to do this too
